# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  (1..3).each do |index|

    config.vm.define "svr#{index}" do |svr|
      svr.vm.hostname = "ubuntu#{index}"

      svr.vm.network :private_network

      # http port forwarding for web server
      #svr.vm.network :forwarded_port, guest: 80, host: "808#{index}", host_ip: "127.0.0.#{index}"
      
      # vagrant's project home directory (C:/Users/jdale/vagrant/ubuntu-22.04) -> /vagrant
      svr.vm.synced_folder ".", "/vagrant"

      svr.vm.provider "vmware_desktop" do |vmware|
        vmware.gui = true
        vmware.memory = 2048
        vmware.cpus = 2
      end

      svr.vm.provision "shell", name: "time", run: "always", path: "files/time.sh"

      svr.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "ansibles/playbook.yml"
      end
  
      svr.vm.provision "shell", name: "bat", privileged: false, inline:<<-DOTFILES
  
        echo alias bat="batcat" >> .bashrc
  
        DOTFILES
  
      svr.vm.provision "shell", name: "tools", path: "files/install.tools.sh"
      
      # install nginx web server
      #svr.vm.provision "shell", path: "files/install.nginx.sh"
      #svr.vm.provision "file", source: "files/index.html", destination: "$HOME/"
      #svr.vm.provision "shell", name: "html", path: "files/install.html.sh"
    
    end

  end

end
