# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "generic/ubuntu2204"
    vm1.vm.hostname = "ubuntu"
    vm1.vm.network :forwarded_port, guest: 80, host: 8080, host_ip: "127.0.0.1"
    vm1.vm.synced_folder "./files", "/home/vagrant/files"
    vm1.vm.synced_folder "./ansibles", "/home/vagrant/ansibles"
  end

  config.vm.provider "vmware_desktop" do |vb|
    vb.gui = true
    vb.memory = 4096
    vb.cpus = 4
  end

  config.vm.provision "shell", name: "time", run: "always", path: "files/time.sh"

  config.vm.provision "shell", name: "ansible", privileged: false, path: "files/install.ansible.sh"

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "/home/vagrant/ansibles/playbook.yml"
  end

  config.vm.provision "shell", name: "bat", privileged: false, inline:<<-DOTFILES

    echo alias bat="batcat" >> .bashrc

    DOTFILES

  config.vm.provision "shell", name: "tools", path: "files/install.tools.sh"
  config.vm.provision "shell", path: "files/install.nginx.sh"
  config.vm.provision "file", source: "files/index.html", destination: "$HOME/"
  config.vm.provision "shell", name: "html", path: "files/install.html.sh"

end